trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=TE-DevOps_java-maven-junit
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '180'
    

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kubectl_1'
    namespace: 'default'
    command: 'exec'
    arguments: |
      -it <sonarqube pode name> -- bash -c "cd /opt/bitnami/sonarqube/extensions/plugins/ ; 
      mkdir reports ;
      java -jar sonar-cnes-report-4.1.1.jar -p <projectkey> -t <token> ;
      mv *.docx *.csv *.md *.xlsx ./reports "
    secretType: 'generic'
  

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kubectl_1'
    namespace: 'default'
    command: 'cp'
    arguments: '<sonarqube pod name>:/opt/bitnami/sonarqube/extensions/plugins/reports $(Pipeline.Workspace)/reports'
    secretType: 'generic'
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/reports'
    artifact: 'Sonarqube analysis report'
    publishLocation: 'pipeline'
